spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: postgres
    password: qazWSX1@
    driver-class-name: org.postgresql.Driver



mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30

jwt:
  signing:
    key: SpringBootTrainingsdfhsdfgsr4gsfgsregsfgsfdg#$%S%G